// Copyright 2024 out of sCope team - Michał Ogiński

#pragma once

#include "NativeGameplayTags.h"

namespace ObsidianGameplayTags
{
	// Abilities
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivationFail_IsDead);
	
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_HitReact);
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Stagger);

	// Kind of Deprecated - using damage types tags for SetByCaller now //
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Damage);
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Heal);

	// Damage Types
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_DamageType_Physical);
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_DamageType_Elemental_Fire);
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_DamageType_Elemental_Cold);
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_DamageType_Elemental_Lightning);
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_DamageType_Chaos);
	
	/** All damage Types stored for convenience */
	OBSIDIAN_API extern const TArray<FGameplayTag> DamageTypes;
	
	// Cooldowns
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Cooldown_HitReact)
	
	// Effects
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_HitReact)
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_Stagger)
	
	// Statuses
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death);
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dying);
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dead);
	
	// Native Input
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Move_Keyboard);
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Move_Mouse);
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_CharacterStatus);

	// Ability Input
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability_Move_Mouse);
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability_Move_Roll);
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability1);
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability2);
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability3);
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability4);
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability5);
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability6);
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability7);
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability8);

	// Data
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_EffectUIInfo)
	
	// UI Data
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_EffectData_Flask_HealthHealing);
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_EffectData_Flask_ManaHealing);

	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_EffectData_Aura_Defiance);

	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_EffectData_Effect_Poison);
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_EffectData_Effect_Chill);
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_EffectData_Effect_Ignite);
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_EffectData_Effect_Shock);
	
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_EffectData_Effect_Curse_ElementalWeakness);
	
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_GlobeData_HealingHealth);
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_GlobeData_RepleanishingMana);

	// Events
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Death);

	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_AdvancedCombat_Hit);
	
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_AbilityMontage_Player_Firebolt)
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_AbilityMontage_Player_Aura)
	
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_AbilityMontage_Socket_RightHandWeapon)
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_AbilityMontage_Socket_LeftHandWeapon)
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_AbilityMontage_Socket_RightHand)
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_AbilityMontage_Socket_LeftHand)
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_AbilityMontage_Socket_BetweenHands)

	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AbilityActivation_Melee);
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AbilityActivation_Ranged);
	
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AbilityActivation_Introduction);

	/**
	 * Tree Orc
	 */
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AbilityActivation_TreeOrc_UnarmedSwing);
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AbilityActivation_TreeOrc_LeapAttack);
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AbilityActivation_TreeOrc_Equip);
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AbilityActivation_TreeOrc_ComboSwing);
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AbilityActivation_TreeOrc_360Swing);
	
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_AbilityMontage_TreeOrc_EquipWeapon);
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_AbilityMontage_TreeOrc_SpawnComboProjectile);
	
	// Attributes UI Data - I will leave it here for now in case I would need it in the future
	/**
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Health);
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_MaxHealth);
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_EnergyShield);
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_MaxEnergyShield);
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_HealthRegeneration);
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_EnergyShieldRegeneration);
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Armor);
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Evasion);
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_FireResistance);
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_MaxFireResistance);
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_ColdResistance);
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_MaxColdResistance);
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_LightningResistance);
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_MaxLightningResistance);
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_ChaosResistance);
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_MaxChaosResistance);
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_CriticalStrikeChance);
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_CriticalStrikeMultiplier);
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_AttackSpeed);
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_CastSpeed);
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_FirePenetration);
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_ColdPenetration);
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_LightningPenetration);
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_ChaosPenetration);
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_FireDamageMultiplier);
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_ColdDamageMultiplier);
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_LightningDamageMultiplier);
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_PhysicalDamageMultiplier);

	
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Mana);
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_MaxMana);
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_ManaRegeneration);
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Strength);
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Intelligence);
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Dexterity);
	OBSIDIAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Faith);
	*/
	
	OBSIDIAN_API FGameplayTag FindTagByString(const FString& TagString, bool bMatchPartialString = false);
}


